judoscale/judoscale-python

- judoscale/core/adapter_api_client.py
Stop relying on deprecated API endpoint.
> Update metrics path from /v1/metrics to /v3/reports

- judoscale/celery/__init__.py
- judoscale/core/adapter.py
- judoscale/core/reporter.py
- judoscale/django/apps.py
- judoscale/django/middleware.py
- judoscale/flask/judoscale.py
- tests/test_reporter.py
This PR introduces a very thin abstraction called `Adapter`. An Adapter wraps metadata about the Judoscale library version and the language/framework version. It also wraps the metrics collector for each integration, as needed.
Adapters are registered with the Reporter which sends metrics as before and also now includes adapter metadata under the `"adapters"` key.
Example payload from the Celery sample app:
```json
{
"dyno": "web.1",
"pid": 85868,
"config": {
"log_level": "DEBUG",
"report_interval_seconds": 15
},
"adapters": {
"judoscale-python": {
"platform_version": "3.10.4",
"adapter_version": "0.1.1"
},
"judoscale-celery": {
"platform_version": "5.2.7",
"adapter_version": "0.1.1"
},
"judoscale-flask": {
"platform_version": "2.2.2",
"adapter_version": "0.1.1"
}
},
"metrics": [
[ …
```
> Include adapter metadata in report payload

- judoscale/core/metric.py
- tests/test_metrics.py
Add nanosecond and microsecond support in `X-Request-Start`.
> Handle ambiguous timestamp values in X-Request-Start

- README.md
- judoscale/celery/collector.py
- tests/test_collectors.py
`judoscale-python` relies on [`SCAN`](https://redis.io/commands/scan/) and its `TYPE` parameter to discover Celery queues. The `TYPE` parameters was only introduced in Redis 6.0.0.
This PR adds Redis version checking to prevent users using earlier Redis versions from seeing a confusing `ResponseError`. Instead, we raise a `RuntimeError` with an appropriate message.
> fix: Handle minimum Redis version

- judoscale/celery/collector.py
- tests/test_collectors.py
This PR fixes fetching Celery configuration options incorrectly due to a botched copy-paste.
> fix: Fix pulling incorrect configuration values for Celery

- judoscale/celery/__init__.py
- judoscale/core/adapter.py
- judoscale/django/middleware.py
- judoscale/flask/judoscale.py
- judoscale/rq/__init__.py
Using `pkg_resources` (distributed with `setuptools`) has been deprecated in favour of newer and improved modules from `importlib`. https://setuptools.pypa.io/en/latest/pkg_resources.html
This PR:
1. swaps out `pkg_resources.get_distribution` for `importlib.metadata.version`, and
2. starts using `importlib.metadata.version` for getting package version information for supported integrations.
> chore: Migrate from setuptools to importlib

- judoscale/celery/collector.py
- tests/test_collectors.py
This PR fixes accessing task properties for tasks that do not have properties. This could happen when an older version of Celery is used or if there are tasks that were enqueued before the Judoscale Celery integration was introduced to the codebase.
> fix: Fix crash when accessing missing Celery task properties

- README.md
- judoscale/celery/collector.py
- judoscale/core/metric.py
- judoscale/rq/collector.py
- sample-apps/django_celery_sample/Procfile.heroku
- sample-apps/django_celery_sample/Procfile.render
- sample-apps/flask_celery_sample/Procfile.heroku
- sample-apps/flask_celery_sample/Procfile.render
- tests/test_collectors.py
This PR adds support for tracking busy jobs with RQ and Celery.
As has been the case with other features, Celery takes a bit more effort than RQ to make things work, and there are caveats. In this case, if `TRACK_BUSY_JOBS` is turned on, the Celery integration will report busy jobs counts only when workers are processing jobs. If there is no work, `self.inspect.active()` will return `None` and no busy metrics will be reported.
If this is a blocker and busy counts should be reported even if there is no work, I can take another look and find a workaround.
> feat: Add support for tracking busy jobs

- README.md
- judoscale/asgi/middleware.py
- poetry.lock
- pyproject.toml
- sample-apps/fastapi_celery_sample/app/main.py
- sample-apps/fastapi_sample/app/main.py
- sample-apps/fastapi_sample/poetry.lock
- sample-apps/fastapi_sample/pyproject.toml
This PR makes `RequestQueueTimeMiddleware` stop relying on Starlette's internals, which makes it more generic and re-usable for any app framework that adheres to the ASGI spec.
FastAPI users should now be installing Judoscale with `pip install 'judoscale[asgi]'`, instead of `pip install 'judoscale[fastapi]'`.
Middleware classes currently included for Quart, Starlette and FastAPI. Users can easily create their own if needed by following the instructions in the README.
> feat: Generic asgi request queue time middleware

- judoscale/asgi/middleware.py
- judoscale/celery/__init__.py
- judoscale/core/config.py
- judoscale/django/apps.py
- judoscale/flask/judoscale.py
- judoscale/rq/__init__.py
- judoscale/rq/apps.py
- sample-apps/django_celery_sample/blog/views.py
- sample-apps/django_rq_sample/blog/views.py
- sample-apps/django_sample/blog/views.py
- sample-apps/fastapi_celery_sample/app/main.py
- sample-apps/fastapi_sample/app/main.py
- sample-apps/flask_celery_sample/app/app.py
- sample-apps/flask_rq_sample/app/app.py
- sample-apps/flask_sample/app.py
- tests/test_config.py
> fix: Handle missing API_BASE_URL

- judoscale/core/reporter.py
- tests/test_reporter.py
Although middleware and extension code already checks whether or not they should be starting the reporter, this PR adds a guard into `Reporter.start()` to prevent the reporter from running in scenarios where folks might be running the adapter in a different way.
> Prevent reporter from running if Config.is_enabled is False

- README.md
- judoscale/core/config.py
- sample-apps/django_sample/bin/heroku
- sample-apps/django_sample/bin/render
- sample-apps/django_sample/django_sample/settings.py
- tests/test_config.py
You can now set Judoscale's log level without a code change using the `JUDOSCALE_LOG_LEVEL` env var. This is useful when troubleshooting your Judoscale adapter behavior.
> Allow setting Judoscale log level using an env var

- README.md
- judoscale/django/redis.py
- judoscale/rq/apps.py
- tests/test_config.py
Heroku Data for Redis premium plans only offer a TLS connection to Redis, which uses self-signed certificates, which require you to configure the verify_mode SSL setting of your Redis client.
This PR fixes the inability to configure this in `JUDOSCALE["REDIS"]` configuration.
> fix: Redis client configuration for RQ

- judoscale/celery/collector.py
- tests/test_collectors.py
This PR fixes two issues with `TRACK_BUSY_JOBS=True`:
- Even if the developer had specified the `QUEUES=[...]` option in their Judoscale configuration, the adapter was reporting busy jobs metrics for other queues as well as the specified queues.
- If no tasks were being processed, no busy jobs metrics were being reported either.
> Report busy job metrics for correct queues

- pyproject.toml
I had a look through the changelog and upgrade notes for Django 5.0 and I don't think there is anything in there that prevents Judoscale from supporting Django 5.x.
> feat: Expand Django version range to cover 5.x.x

- judoscale/celery/collector.py
At the moment, we'r logging the relatively unhelpful warning `WARNING - [judoscale] Unable to find published_at in task properties for task ID None.`, which isn't very useful for debugging.
This PR adds the queue name from which the task in question was pulled from.
> Log Celery queue name when published_at isn't found in task properties

- judoscale/celery/collector.py
- tests/test_collectors.py
In certain configurations the adapter library outputs a large volume of warning logs that look something like this:
> WARNING - [judoscale] Unable to find `published_at` in task properties for task ID None in queue e752fa70-f772-3c04-b05d-79b2a79ce766.reply.celery.pidbox.
This happens because `e752fa70-f772-3c04-b05d-79b2a79ce766.reply.celery.pidbox` is incorrectly detected as a user queue. Consequently, the adapter tries to inspect the queue to determine queue latency, but the items in there do not correspond to Celery tasks, which causes the warning log lines to get emitted by the adapter library.
This PR tightens up the mechanism by which the adapter tries to discover the Celery queues to monitor.
> fix: Improve automatic queue detection for Celery

- sample-apps/docker-compose.yml
Make it possible to run the dependency(ies) for the sample apps in an isolated environment — Docker.
> chore: Add docker-compose.yml for sample apps

- poetry.lock
- pyproject.toml
Flask 3 was released a while back but our `pyproject.toml` still specifies `<3.0.0` which prevents folks from using Flask 3+ with Judoscale. This PR bumps the Flask extra to `<4.0.0`.
> fix: Bump Flask extra to <4.0.0

- judoscale/core/config.py
- tests/test_config.py
We're early-testing Railway as a platform integration, this adds detection for the Railway environment to report the runtime container as the Railway Replica ID.
It also changes the Render configuration to favor JUDOSCALE_URL, as we are now requiring that to be set for new apps/services, deprecating the service ID api-based URL. (which is still supported by current apps and our backend)
Related:
- https://github.com/judoscale/judoscale-ruby/pull/230
- https://github.com/judoscale/judoscale-node/pull/54
> Configure runtime container for Railway

- judoscale/core/config.py
- tests/test_config.py
Adds detection for the Fly environment to report the runtime container as the Fly Machine ID.
(The Fly.io integration is currently in early-testing)
<details><summary>Sample ENV vars</summary>
<p>
</p>
</details>
> Configure runtime container for Fly.io

- judoscale/core/metric.py
- tests/test_collectors.py
Our backend expects the metric identifiers to be reported from all our libraries as "short" versions, but we were sending `queue_time` instead here, which the backend is translating correctly but shouldn't have to.
The backend will continue to have legacy support for `queue_time` for a while for current adapters out there, but this changes the Python adapter going forward  to report metrics using `qt` to match our other adapters.
https://github.com/judoscale/judoscale-ruby/blob/ad739e4cf41e44a8e79c502afc02ffa461c5f8e1/judoscale-ruby/lib/judoscale/request_middleware.rb#L31
https://github.com/judoscale/judoscale-node/blob/408fe1db8e153b9f0d83cab3435b22d2e3a23e70/packages/express/src/index.js#L15 
https://github.com/judoscale/judoscale-node/blob/408fe1db8e153b9f0d83cab3435b22d2e3a23e70/packag …
> Report queue time metric with the expected `qt` identifier

- judoscale/core/__init__.py
- judoscale/core/reporter.py
- sample-apps/django_sample/Procfile.heroku
- sample-apps/django_sample/blog/views.py
- sample-apps/django_sample/tests/tests.py
- sample-apps/fastapi_sample/Procfile.heroku
- sample-apps/fastapi_sample/app/main.py
- sample-apps/fastapi_sample/tests.py
- sample-apps/flask_sample/Procfile.heroku
- sample-apps/flask_sample/app.py
- sample-apps/flask_sample/tests.py
- tests/test_reporter.py
I tested by running the Django server (here with the Procfile changed to run 3 workers and 2 threads each) with `bin/heroku | grep Starting` to filter just the messages we cared about, and then executed `hey` against the server to hit it with a few concurrent requests: `hey 'http://localhost:5006/?sleep=t' -n 20 -c 5`
Behavior on main:
```
% bin/heroku | grep Starting
1:55:39 PM web.1   |  INFO - [judoscale] Starting reporter for process 11661
1:55:39 PM web.1   |  [2025-08-04 16:55:39 +0000] [11661] [INFO] Starting gunicorn 20.1.0
1:55:42 PM web.1   |  INFO - [judoscale] Starting reporter for process 11664
1:55:42 PM web.1   |  INFO - [judoscale] Starting reporter for process 11666
1:55:42 PM web.1   |  INFO - [judoscale] Starting reporter for process 11666
1:55:42 PM web.1   |  INFO - …
```
> fix: Ensure reporter thread only starts once per process
